### ISSUE TITLE
Help: I'm having trouble getting mods to load

### ISSUE THREAD

**Issue by McManners** [Reloaded-Project/Reloaded-II#101]
[19:05:36] [Reloaded] Create Loader | Time: 89ms
[19:05:36] [Reloaded] Create Loader Host (Async) | Time: 145ms
[19:05:36] [Reloaded] Setting Up Hooks (Async) | Time: 156ms
[19:05:36] [Reloaded] Failed to Load Reloaded-II.
Reloaded II was unable to find all dependencies for the mod(s) to be loaded.
Aborting load.
Missing dependencies: reloaded.sharedlib.hooks
   at Reloaded.Mod.Loader.Loader.GetDependenciesForMods(IEnumerable`1 mods, IEnumerable`1 allMods, String modDirectory)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\Diego\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2021-08-16 19.05.36 ~ Tsonic_win.txt
[19:06:02] [Reloaded] ExitProcess Hook: Log End

So the game now loads, but the mods aren't, I double-checked and I do have the dependencies needed, yet for some odd reasons no mods load, not even the controller. I do have a log file, while I understand it a bit I feel I might be missing something else from it.

![Screenshot (10)](https://user-images.githubusercontent.com/17581132/129645979-583e048e-29e8-4d62-84fc-2552e4b5901b.png)

**Comment by Sewer56** [comment]
Maybe your AV took out some mod files alongside the EXE.
It does seem like you have the mod on your screenshot; maybe try deleting it and let Reloaded re-download it; either through the check updates button in `Download Mods` or by restarting the launcher.

Please don't open new issues unnecessarily; respond to existing issues instead.
