### ISSUE TITLE
Help: Running latest 1.21.0 through wine

### ISSUE THREAD

**Issue by eskay993** [Reloaded-Project/Reloaded-II#140]
**Describe the Issue**
I'm trying the 1.21.0 version through wine. Everything installs just fine using the `Setup.exe` version, including .NET 7, however when I launch Reloaded I get the exception listed below and it does not update mods or downloads any mod dependencies. Reloaded seems to run fine otherwise, it just that the downloads don't work.

If I manually download and install the mod dependencies, everything works fine.

I tested the exact same mod with earlier versions of Reloaded and everything works fine there too - mod/dependencies are downloaded correctly.

Also tested 1.21.0 on Windows just to see, and everything works there.

From what I can tell, `MsQuicApi` relates to .NET 7. It may well be simply that wine does not full support .NET 7 yet, but thought I would ask to see if anyone has any suggestions?

Many thanks.

**Additional Resources**
```
Fatal error. 0xC0000005
   at System.Net.Quic.MsQuicApi..cctor()
   at System.Net.Quic.QuicConnection.get_IsSupported()
   at System.Net.Http.HttpConnectionPool..ctor(System.Net.Http.HttpConnectionPoolManager, System.Net.Http.HttpConnectionKind, System.String, Int32, System.String, System.Uri)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(System.Net.Http.HttpRequestMessage, System.Uri, Boolean, Boolean, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.RedirectHandler+<SendAsync>d__4, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendAsync>d__4 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.RedirectHandler+<SendAsync>d__4, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendAsync>d__4 ByRef)
   at System.Net.Http.RedirectHandler.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.Send(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationToken)
   at System.Net.HttpWebRequest+<SendRequest>d__196.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.HttpWebRequest+<SendRequest>d__196, System.Net.Requests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendRequest>d__196 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.HttpWebRequest+<SendRequest>d__196, System.Net.Requests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendRequest>d__196 ByRef)
   at System.Net.HttpWebRequest.SendRequest(Boolean)
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(System.Net.WebRequest)
   at System.Net.WebClient.OpenRead(System.Uri)
   at Reloaded.Mod.Launcher.Lib.Update.CheckForInternetConnection()
   at Reloaded.Mod.Launcher.Lib.Update..cctor()
   at Reloaded.Mod.Launcher.Lib.Update.get_HasInternetConnection()
   at Reloaded.Mod.Launcher.Lib.Update+<CheckForLoaderUpdatesAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Reloaded.Mod.Launcher.Lib.Update+<CheckForLoaderUpdatesAsync>d__4, Reloaded.Mod.Launcher.Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<CheckForLoaderUpdatesAsync>d__4 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Reloaded.Mod.Launcher.Lib.Update+<CheckForLoaderUpdatesAsync>d__4, Reloaded.Mod.Launcher.Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<CheckForLoaderUpdatesAsync>d__4 ByRef)
   at Reloaded.Mod.Launcher.Lib.Update.CheckForLoaderUpdatesAsync()
   at Reloaded.Mod.Launcher.Lib.Setup+<CheckForUpdatesAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Reloaded.Mod.Launcher.Lib.Setup+<CheckForUpdatesAsync>d__15, Reloaded.Mod.Launcher.Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<CheckForUpdatesAsync>d__15 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Reloaded.Mod.Launcher.Lib.Setup+<CheckForUpdatesAsync>d__15, Reloaded.Mod.Launcher.Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<CheckForUpdatesAsync>d__15 ByRef)
   at Reloaded.Mod.Launcher.Lib.Setup.CheckForUpdatesAsync()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__273_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
wine: Call from 7BC2F950 to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting
```

**Comment by Sewer56** [comment]
Based on this stack trace, it's related to QUIC, and thus HTTP/3 in turn.
Let me see if I can find a way to disable HTTP/3 in the runtime.

**Comment by Sewer56** [comment]
Can you test this build? [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/files/9842745/Release.zip)

I disabled HTTP/3 support in this build; it should hopefully skip the problematic code path.

**Comment by eskay993** [comment]
Thanks for the quick response. Just tested the build and works flawlessly through wine! Everything downloads correctly. Thanks so much for that,

**Comment by Sewer56** [comment]
This fix is already present in the latest release version, so there's nothing extra for you to do there by the way :p
