### ISSUE TITLE
Persona 5 Essentials Issue.

### ISSUE THREAD

**Issue by whoskale** [Reloaded-Project/Reloaded-II#173]
I've been watching videos and reading guides in order to set up P5R for modding, and when I download Persona 5 Essentials, there's no mod config that i could enable mods?

(Side note, my reloaded ii crashes often upon launching.)
![Screenshot_9](https://user-images.githubusercontent.com/120533510/207478205-2381fc08-30ef-4702-bc8d-259410f9e67e.png)

**Comment by Novationo** [comment]
I am currently facing the same issue, I had mods working previously by installing manually but decided to attempt to move over to Reloaded-II (I verified my game, so i only have the vanilla BASE.CPK, and EN.CPK).
I have tried multiple times to get reloaded/P5REssentials working but it keeps failing, I've attempted with _just_ the Persona Essentials Mod and Jack Sexo like as show in the tutorial on GameBanana. Along with installing other dependencies like `CRI FileSystem V2 Hook` and `AWB Emulator Support for CRI FileSystem V2 Hook`. Ive also deleted/redownloaded them as mentioned in the comments of the P5REssentials mod on GameBanana.

Attached is one of my many mod logs, where `p5rpc.modloader` just doesnt load, so P5R launches vanilla
```[22:01:26] [Reloaded] Create Loader | Time: 49ms
[22:01:26] [Reloaded] Loaded: reloaded.sharedlib.hooks in 5ms
[22:01:26] [Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\P5R\P5R.exe
[22:01:26] [Reloaded] [LoaderAPI] Warning: GetController<IStartupScanner> returned null.
[22:01:26] Error while starting mod: p5rpc.modloader
[22:01:26] [Reloaded] Failed to Load Reloaded-II.
Object reference not set to an instance of an object.
   at p5rpc.modloader.Mod..ctor(ModContext context)
   at p5rpc.modloader.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\Nova\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2023-01-11 05.01.26 ~ P5R.txt
[22:01:27] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[22:01:27] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[22:01:27] [R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[22:01:27] [Reloaded] Setting Up Hooks (Async) | Time: 178ms
[22:01:29] [Reloaded] ExitProcess Hook: Log End```

I may also of just timed this badly as patch 1.03 just rolled out for P5R, but mods were still working with my manual modded BASE.CPK.

**Comment by Sewer56** [comment]
Based on this error log, try removing `Reloaded.Memory.Sigscan for Reloaded II` and let it re-download.

**Comment by Novationo** [comment]
Just tried that and after redownloading it still crashes shortly after pressing "Launch Application", I also redownloaded `reloaded.universal.fileemulationframework` and `reloaded.sharedlib.hooks` to see if that would do it, but i did not.
I also reran/installed everything in the Persona Prerequisite installer if that helps.

```[22:29:30] [Reloaded] Create Loader | Time: 49ms
[22:29:30] [Reloaded] Loaded: reloaded.sharedlib.hooks in 5ms
[22:29:30] [Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\P5R\P5R.exe
[22:29:30] [Reloaded] [LoaderAPI] Warning: GetController<IStartupScanner> returned null.
[22:29:30] Error while starting mod: p5rpc.modloader
[22:29:30] [Reloaded] Failed to Load Reloaded-II.
Object reference not set to an instance of an object.
   at p5rpc.modloader.Mod..ctor(ModContext context)
   at p5rpc.modloader.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\Nova\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2023-01-11 05.29.30 ~ P5R.txt
[22:29:30] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[22:29:30] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[22:29:30] [R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[22:29:30] [Reloaded] Setting Up Hooks (Async) | Time: 181ms
[22:29:43] [Reloaded] ExitProcess Hook: Log End```

**Comment by Sewer56** [comment]
According to the 3rd line of your log, it's the mod I listed earlier that's missing or did not load correctly

**Comment by Novationo** [comment]
After redownloading it, i went to "Manage mods" and [saw it P5R wasn't highlighted to use it](https://user-images.githubusercontent.com/80179204/211730701-f3a2a7c0-7e7b-4db6-96fa-81f844cc4a60.png), after it appeared in the P5R Mod list it still failed to launch. 
But I looked at the dependencies for P5REssentials and [marked everything on it as a dependency](https://user-images.githubusercontent.com/80179204/211729454-98b901a0-f6c1-4832-b8e5-6cae487208b7.png) (except Jack Sexo), and it worked!

Ty for the help!
