### ISSUE TITLE
Help: Please help me with Reload II on P5R

### ISSUE THREAD

**Issue by KatzKai** [Reloaded-Project/Reloaded-II#174]
Although I was using this pretty smoothly on P4. But in P5R, Reload II didn't seem to work, even after freshly install. BTW, thanks for your work.
Here is my log:

[15:00:34] [Reloaded] Create Loader | Time: 33ms
[15:00:34] [Reloaded] Loaded: Reloaded.Memory.SigScan.ReloadedII in 5ms
[15:00:34] [Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[15:00:34] Starting FileEmulationFramework
[15:00:34] Error while starting mod: reloaded.universal.fileemulationframework
[15:00:34] [Reloaded] Failed to Load Reloaded-II.
Object reference not set to an instance of an object.
   at FileEmulationFramework.Utilities.NativeFunctions..ctor(IntPtr ntCreateFile, IntPtr ntReadFile, IntPtr ntSetInformationFile, IntPtr ntQueryInformationFile, IntPtr closeHandle, IntPtr getFileType, IReloadedHooks hooks)
   at FileEmulationFramework.Utilities.NativeFunctions.GetInstance(IReloadedHooks hooks)
   at FileEmulationFramework.Mod..ctor(ModContext context)
   at FileEmulationFramework.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadWithExportsIntoCurrentALC(String modId)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by Sewer56** [comment]
I'd delete File Emulation Framework mod and Reloaded SharedLib Hooks mod and let the launcher re-download them.

The hooks lib isn't being loaded according to log before FEF, which means you might have edited the mod and unchecked the dependency from the list or hooks mod just didn't install.

**Comment by KatzKai** [comment]
Wow, thanks a lot, it's work properly now
