### ISSUE TITLE
Help: I tried to use Reloaded ii as usual but when I tried to start it, it said file emulation framework error

### ISSUE THREAD

**Issue by Tibbles09** [Reloaded-Project/Reloaded-II#196]
**My reloaded had been working perfectly fine but then for some reason today, it totally flipped on me. It gave me some file emulation framework error. I have no idea what's wrong but here is the log given to me.** 

_[16:16:48] [Reloaded] Create Loader | Time: 43ms
[16:16:49] Updating Config w/ HasExports & CanUnload.
[16:16:49] [Reloaded] Loaded: reloaded.sharedlib.hooks in 1338ms
[16:16:49] [Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\P5R\P5R.exe
[16:16:49] [Reloaded] Loaded: Reloaded.Memory.SigScan.ReloadedII in 65ms
[16:16:49] Updating Config w/ HasExports & CanUnload.
[16:16:49] Starting FileEmulationFramework
[16:16:49] Error while starting mod: reloaded.universal.fileemulationframework
[16:16:49] [Reloaded] Failed to Load Reloaded-II.
Entry point was not found.
   at FileEmulationFramework.Utilities.NativeFunctions..ctor(IntPtr ntCreateFile, IntPtr ntReadFile, IntPtr ntSetInformationFile, IntPtr ntQueryInformationFile, IntPtr closeHandle, IReloadedHooks hooks)
   at FileEmulationFramework.Utilities.NativeFunctions.GetInstance(IReloadedHooks hooks)
   at FileEmulationFramework.Mod..ctor(ModContext context)
   at FileEmulationFramework.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\TimBu\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2023-03-04 23.16.48 ~ P5R.txt
[16:16:49] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[16:16:49] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[16:16:50] [R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[16:16:50] [Reloaded] Setting Up Hooks (Async) | Time: 515ms_

**I'm not sure if it is a norton issue that they starting being all annoying with my files or if it's something else. I couldn't figure out how to do a clean uninstall (I know, I'm an idiot) and I tried downloaded reloaded again and the same issue persisted. Hopefully someone can provide me some insight. Thank you!**

**Comment by Sewer56** [comment]
Someone ran into the same issue as you a few hours before that. Their Antivirus flipped out and started pretty much randomly deleting Reloaded and mod files en masse. 

I'd check Antivirus logs, see if you can restore the files; otherwise you might have some luck redownloading the mod(s) using these hyperlinks [copy paste them into browser].

`r2:https://github.com/Sewer56/FileEmulationFramework/releases/download/2.3.2/FileEmulationFramework2.1.3.7z`

`r2:https://github.com/Sewer56/FileEmulationFramework/releases/download/2.3.2/AWB.Stream.Emulator2.1.2.7z`
