### ISSUE TITLE
I get this message when trying to run Silent Hill.

### ISSUE THREAD

**Issue by petran79** [Reloaded-Project/Reloaded-II#206]
Game runs despite this message but does this mean that the Voice and Sound Enhancement Pack are not activated?

[00:36:36] [Reloaded] Create Loader | Time: 86ms
[00:36:36] [Reloaded] Loaded: reloaded.sharedlib.hooks in 9ms
[00:36:36] [Reloaded] Current Process Location: D:\games\silenthill3\sh3.exe
[00:36:36] [Reloaded] Loaded: Reloaded.Universal.DInputPleaseCooperate in 451ms
[00:36:36] Updating Config w/ HasExports & CanUnload.
[00:36:36] Error while starting mod: reloaded.universal.fileemulationframework
[00:36:36] Starting FileEmulationFramework
[00:36:36] [Reloaded] Setting Up Hooks (Async) | Time: 18ms
[00:36:36] [Reloaded] Failed to Load Reloaded-II.
Entry point was not found.
   at FileEmulationFramework.Utilities.NativeFunctions..ctor(IntPtr ntCreateFile, IntPtr ntReadFile, IntPtr ntSetInformationFile, IntPtr ntQueryInformationFile, IntPtr closeHandle, IReloadedHooks hooks)
   at FileEmulationFramework.Utilities.NativeFunctions.GetInstance(IReloadedHooks hooks)
   at FileEmulationFramework.Mod..ctor(ModContext context)
   at FileEmulationFramework.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

Another issue is that after I updated Reloader II, it gave me an option to automatically update all existing mods. However if I click Download, I get this message and application crashes. I have to ignore the updates everytime
![crash](https://user-images.githubusercontent.com/8232210/227659206-039c55ee-1640-43b1-9166-509c598dea5a.jpg)
![crash2](https://user-images.githubusercontent.com/8232210/227659201-e7a978fc-a87f-4991-8859-d017bf116785.jpg)

**Comment by petran79** [comment]
I have currently av disabled, including Windows Defender. Had also  not updated reloader for many months since summer, so something must have gone wrong in the update process.
I can update mods manually at least. 

I'll try disabling the sh3 enhancement fix patch on games directory to see if this conflicts with reloaded
