### ISSUE TITLE
Help: Please help me with Sonic Heroes

### ISSUE THREAD

**Issue by shadow64dd** [Reloaded-Project/Reloaded-II#216]
[00:23:32] [Reloaded] Create Loader | Time: 56ms
[00:23:32] [Reloaded] Create Loader Host (Async) | Time: 49ms
[00:23:32] [Reloaded] Failed to Load Reloaded-II.
One or more errors occurred. (Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.) (Unable to load one or more of the requested types.
Could not load type 'Reloaded.Mod.Interfaces.IConfiguratorV1' from assembly 'Reloaded.Mod.Interfaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.) (Unable to load one or more of the requested types.
Could not load type 'Reloaded.Mod.Interfaces.IConfiguratorV1' from assembly 'Reloaded.Mod.Interfaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.) (Unable to load one or more of the requested types.
Could not load type 'Reloaded.Mod.Interfaces.IConfiguratorV1' from assembly 'Reloaded.Mod.Interfaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.) (Unable to load one or more of the requested types.
Could not load type 'Reloaded.Mod.Interfaces.IConfiguratorV1' from assembly 'Reloaded.Mod.Interfaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.) (Unable to load one or more of the requested types.
Could not load type 'Reloaded.Mod.Interfaces.IConfiguratorV1' from assembly 'Reloaded.Mod.Interfaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, Action`2 body)
   at Reloaded.Mod.Loader.Mods.PluginManager.PreloadAssemblyMetadata(List`1 configPathTuples)
   at Reloaded.Mod.Loader.Mods.PluginManager.ExecuteWithStopwatch[T](String message, Action`1 code, T parameter)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by Sewer56** [comment]
You're probably using an outdated version of the loader with a newer mod.

**Comment by shadow64dd** [comment]
> You're probably using an outdated version of the loader with a newer mod.

i managed to get it to work suddenly but now i have a new issue

Crash Address:BCD330

**Comment by shadow64dd** [comment]
> You're probably using an outdated version of the loader with a newer mod.

actually, let me just send the crash dump it gave me that would probably help more

[01:03:29] [Reloaded] Create Loader | Time: 54ms
[01:03:29] [Reloaded] Loaded: reloaded.sharedlib.hooks in 10ms
[01:03:29] [Reloaded] Current Process Location: D:\Sonic\Sonic Heroes\SONICHEROES\Tsonic_win.exe
[01:03:29] [Reloaded] Loaded: Reloaded.Memory.SigScan.ReloadedII in 7ms
[01:03:29] [Reloaded] Loaded: criware.filesystem.hook in 6ms
[01:03:29] [Reloaded] Loaded: reloaded.universal.redirector in 133ms
[01:03:29] [Reloaded] Setting Up Hooks (Async) | Time: 177ms
[01:03:29] [Reloaded] Loaded: sonicheroes.skins.metalsonicfix in 9ms
[01:03:29] [Reloaded] Loaded: sonicheroes.utils.unlimitedobjectdrawdistance in 47ms
[01:03:29] [Reloaded] Loaded: sonicheroes.effect.shurikenfix in 0ms
[01:03:29] [Reloaded] Loaded: sonicheroes.gamefiles.consolerestoration in 1ms
[01:03:29] [Reloaded] Loaded: Xbox One Buttons in 0ms
[01:03:29] [Reloaded] Loaded: sonicheroes.gamefiles.xboxmedia in 0ms
[01:03:29] [Reloaded] Loaded: reloaded.sharedlib.csharp.prs in 4ms
[01:03:29] [Reloaded] Loaded: sonicheroes.utils.toner in 37ms
[01:03:29] [Reloaded] Loaded: sonicheroes.utils.discordrpc in 27ms
[01:03:29] [Reloaded] Loaded: sonicheroes.essentials.graphics in 56ms
[01:03:30] [Reloaded] Loaded: sonicheroes.guis.widescreenrevamp in 2ms
[01:03:30] [Reloaded] Loaded: sonicheroes.gamefiles.characteroverhaul in 1ms
[01:03:30] [Reloaded] Loaded: sonicheroes.controller.hook in 17ms
[01:03:30] [Reloaded] Loaded: sonicheroes.controller.hook.xinput in 50ms
[01:03:30] [Reloaded] Loaded: sonicheroes.controller.hook.postprocess in 24ms
[01:03:30] [Reloaded] Loaded: sonicheroes.controller.hook.custom in 364ms
[01:03:30] [Reloaded] Loaded: sonicheroes.audio.dialoguevolumefix in 0ms
[01:03:30] [Reloaded] Loaded: sonicheroes.gamefiles.hdrings in 5ms
[01:03:30] [Reloaded] Loaded: sonicheroes.effects.heroesoutline in 0ms
[01:03:30] [CriFsHook] Successfully hooked BuildFileTableFnPtr at 6D63B0
[01:03:30] [CriFsHook] Successfully hooked GetFileEntryFromFilePathFnPtr at 6D00F0
[01:03:30] [Reloaded] Loading Mods (Total) | Time: 928ms
[01:03:30] [Reloaded] Total Loader Initialization Time: 1023ms
[01:03:33] [Reloaded] Crashed. Generating Crash Dump. Might take a while.

**Comment by Enigma2442** [comment]
I have the same issue as [shadow64dd] where the mods WILL load but it always creates a crash dump file every time SONIC HEROES loads up. It wont do it with Riders and I tried doing it without any mods and it still sends a crash file while loading the game without any issues.

**Comment by Sewer56** [comment]
If the crash address is BCD330, try disabling Data Execution Prevention (DEP) for TSonic_win.exe

**Comment by Enigma2442** [comment]
I have tried that and when its disabled, it won't launch the game
whatsoever and give 2 error crashes

**Comment by Enigma2442** [comment]
I will do that today when I get home. Does GitHub allow video files? If
not, should I upload to YT as a private video or something?

**Comment by Sewer56** [comment]
Whichever works for you, honestly, you can try both.

**Comment by Enigma2442** [comment]
https://www.youtube.com/watch?v=4FnhlPtyGwI

Tried sending it through here but I couldn't compress i t below 10MB.

**Comment by Sewer56** [comment]
Not sure if it'll fix your strange case of getting an error (before game proceeds to run just fine); but you probably have a pre-modded copy. I can tell this from the fact you're running 2 widescreen hacks at the same time, which squishes your game.

Here's how a clean game folder looks like
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/81fbf0e6-9d0f-4a2a-b27c-5add773ea358)

Chances are, you can get rid of any existing pre-modifications by deleting `dinput8.dll` and `scripts` folder you may have.

**Comment by Enigma2442** [comment]
The other Widescreen hack wasnt actually used. I just had it there as a
backup before I found out about Reloaded a WHILE back. I did remove them to
see if anything changed but it has not

**Comment by Sewer56** [comment]
Do you get the error without mods enabled too? Curious about this one.

**Comment by Enigma2442** [comment]
So I re-did the EXE and I guess you were right about the double widescreen hack. Its been rectified yet the error continues. When disabling the mods, it launches the base game with the same crash. If I run the game from the EXE, no errors but also, no mods enabled.

**Comment by Sewer56** [comment]
I looked inside the EXE and there shouldn't be any code at that address, that's pretty weird.

Can you upload the following:
- Crash dump created with your error (.dmp) file
- Screenshot of game folder
- The EXE file you're using.

Technically Reloaded shouldn't touch any game code out of the box, so I'm actually really curious what is going on. Hopefully the crash dump contains a stack trace which will tell me how the code got there.

----

This is kind of an interesting situation, I've never seen someone error out when running without mods.

**Comment by Enigma2442** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/38794388/546261c3-3794-4c07-9546-fb65481d199a)

As for EXE and DMP, I had to upload to Drive Folder:
https://drive.google.com/file/d/19e38YOyBI9Qomy6kgR0ZIg-VYN9NPeuX/view?usp=drive_link

I will delete it after you take a look at it

**Comment by Enigma2442** [comment]
If it makes a difference, It used to work just fine without the crash before Reloaded Updated a few months ago. After that, any new release would give that error. Even if I went back to the previous version, it would do it. I even did a CLEAN install of Reloaded just to make sure.

**Comment by Enigma2442** [comment]
UPDATE: As I re-added the EXE from the PC Collection, it kept failing but after a while, the error stopped. It just started to work again. No Crashes and I still can't say why. It was all weird. Just thought I would let you know and maybe other people who experience the same issues can know too!

**Comment by Sewer56** [comment]
This is certainly a weird one off :sweat_smile:

**Comment by Enigma2442** [comment]
> I just got back, and this is certainly a weird one off 😅

Tell me about it. Wonder what it is about. Either way, I thank you for the time to help and I love your work!

**Comment by Sewer56** [comment]
Can't say; I didn't get to download the Crash Dump before it was deleted.

**Comment by Enigma2442** [comment]
Would you still want the dump?

**Comment by Sewer56** [comment]
If it works, it works. Normally I'd be pedantic about checking these things but I've been pretty busy lately :sweat_smile:

**Comment by Enigma2442** [comment]
That'd understandable. I still appreciate it. Keep up the good work!
