### ISSUE TITLE
Trying to run P5R with mods (but failing)

### ISSUE THREAD

**Issue by Ebicmodder** [Reloaded-Project/Reloaded-II#242]
when I tried playing p5r with mods countless times I have been hit with this message:
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/139690923/48f8240d-3ce0-411e-905e-4910c132fe3f)
I don't know what this error means.
the game still boots tho it just doesn't run the mods. I have reinstalled reload countless times and I get the same issue or another issue

**Comment by Sewer56** [comment]
Can you post the full uncropped message?

**Comment by Ebicmodder** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/139690923/37d85762-c17a-4925-a2cb-fc12befdd16f)
log:
[14:26:06] [Reloaded] Create Loader | Time: 48ms
[14:26:06] [Reloaded] Loaded: reloaded.sharedlib.hooks in 8ms
[14:26:06] [Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\P5R\P5R.exe
[14:26:06] [Reloaded] DLL Not Found! Reloaded.Memory.SigScan.ReloadedII.dll
Mod Name: Library: Reloaded.Memory.Sigscan for Reloaded II, Mod ID: Reloaded.Memory.SigScan.ReloadedII
Please re-download the mod. It is either corrupt or you may have downloaded the source code by accident.
[14:26:06] [Reloaded] Loaded: Reloaded.Memory.SigScan.ReloadedII in 0ms
[14:26:06] Starting FileEmulationFramework
[14:26:06] [Reloaded] Loaded: reloaded.universal.fileemulationframework in 159ms
[14:26:06] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[14:26:06] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[14:26:06] Starting AWB.Stream.Emulator
[14:26:06] [Reloaded] [LoaderAPI] Warning: GetController<IScannerFactory> returned null.
[14:26:06] Error while starting mod: reloaded.universal.fileemulationframework.awb
[14:26:06] [R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[14:26:06] [Reloaded] Setting Up Hooks (Async) | Time: 195ms
[14:26:06] [Reloaded] Failed to Load Reloaded-II.
Object reference not set to an instance of an object.
   at AWB.Stream.Emulator.Mod..ctor(ModContext context)
   at AWB.Stream.Emulator.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by Sewer56** [comment]
Seems like you're missing a file in one of your mods for whatever reason.

Open the `Mods` folder in your `Reloaded` folder and delete `Reloaded.Memory.SigScan.ReloadedII`, it should automatically re-download next time you start a game.

**Comment by Ebicmodder** [comment]
is this the thing i need to delete?
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/139690923/5218963f-e9d2-4f75-8c81-e89a46b9bbdc)

**Comment by Sewer56** [comment]
Yeah, give it a go

**Comment by Ebicmodder** [comment]
now i have another problem
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/139690923/04fac4a0-48ec-4bd9-bada-0f56c7493021)

**Comment by Ebicmodder** [comment]
and here's the Log:
[14:56:30] [Reloaded] Create Loader | Time: 49ms
[14:56:30] [Reloaded] Loaded: reloaded.sharedlib.hooks in 8ms
[14:56:30] [Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\P5R\P5R.exe
[14:56:30] Updating Config w/ HasExports & CanUnload.
[14:56:30] [Reloaded] Loaded: Reloaded.Memory.SigScan.ReloadedII in 33ms
[14:56:30] Starting FileEmulationFramework
[14:56:30] [Reloaded] Loaded: reloaded.universal.fileemulationframework in 130ms
[14:56:30] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[14:56:30] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[14:56:30] Starting AWB.Stream.Emulator
[14:56:30] [Reloaded] Loaded: reloaded.universal.fileemulationframework.awb in 16ms
[14:56:30] [R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[14:56:30] [Reloaded] Setting Up Hooks (Async) | Time: 206ms
[14:56:30] Updating Config w/ HasExports & CanUnload.
[14:56:30] [Reloaded] Loaded: crifs.v2.hook in 58ms
[14:56:30] [Reloaded] Failed to Load Reloaded-II.
Unable to load one or more of the requested types.
Could not load file or assembly 'FileEmulationFramework.Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadModPlugin(PathTuple`1 mod, String dllPath, Boolean searchForExports, Type& entryPointType, Type& exportsType)
   at Reloaded.Mod.Loader.Mods.PluginManager.PrepareDllMod(PathTuple`1 mod)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by Sewer56** [comment]
Same issue, seems you're missing a file or two. Not really sure why your downloads are borked; the log doesn't have mod name but it's probably one of the following:

- `reloaded.universal.fileemulationframework.pak`
- `reloaded.universal.fileemulationframework.bf`
- `p5rpc.modloader`

If in doubt, delete all, they'll auto download.

**Comment by Ebicmodder** [comment]
I deleted all and i got the same error

**Comment by Sewer56** [comment]
Gimme a few moments...

**Comment by Ebicmodder** [comment]
Well, i cleared everything in my mods folder, reopened reload and some things installed and now it seems to be working. ill comment again if anything goes wrong
