### ISSUE TITLE
help

### ISSUE THREAD

**Issue by arink22** [Reloaded-Project/Reloaded-II#262]
[18:32:15] [Reloaded] Create Loader | Time: 317ms
[18:32:15] [Reloaded] Create Loader Host (Async) | Time: 165ms
[18:32:16] [Reloaded] Failed to Load Reloaded-II.
One or more errors occurred. (Unable to load one or more of the requested types.
Could not load type 'Reloaded.Mod.Interfaces.IConfiguratorV1' from assembly 'Reloaded.Mod.Interfaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.) (Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. El sistema no puede encontrar el archivo especificado.)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, Action`2 body)
   at Reloaded.Mod.Loader.Mods.PluginManager.PreloadAssemblyMetadata(List`1 configPathTuples)
   at Reloaded.Mod.Loader.Mods.PluginManager.ExecuteWithStopwatch[T](String message, Action`1 code, T parameter)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\cock\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2023-10-22 18.32.15 ~ Tsonic_win.txt
[18:32:16] [Reloaded] Setting Up Hooks (Async) | Time: 790ms

**Comment by Sewer56** [comment]
Either your .NET Runtime download is borked, or Reloaded install is borked.

Try the following:
- Extract [Latest Release](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.0/Release.zip) over your Reloaded folder.
- Manually Install .NET Runtime(s) [x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-rc.2-windows-x64-installer) AND [x86](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-rc.2-windows-x86-installer)

**Comment by arink22** [comment]
i did that but now this happens
[21:14:53] [Reloaded] Create Loader | Time: 117ms
[21:14:53] [Reloaded] Loaded: reloaded.sharedlib.hooks in 28ms
[21:14:53] [Reloaded] Current Process Location: C:\Program Files\Sega\SONICHEROES\Tsonic_win.exe
[21:14:53] [Reloaded] Failed to Load Reloaded-II.
Reloaded II was unable to find all dependencies for the mod(s) to be loaded.
Aborting load.
Missing dependencies: reloaded.sharedlib.csharp.prs,Reloaded.Memory.SigScan.ReloadedII
   at Reloaded.Mod.Loader.Loader.GetDependenciesForMods(IEnumerable`1 mods, IEnumerable`1 allMods, String modDirectory)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\Alejandro\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2023-11-05 02.14.53 ~ Tsonic_win.txt
[21:14:54] [Reloaded] Setting Up Hooks (Async) | Time: 359ms

**Comment by Sewer56** [comment]
You might be missing some files.
In your `Mods` folder where the Reloaded-II launcher is stored, delete the following:

- `reloaded.sharedlib.csharp.prs`
- `Reloaded.Memory.SigScan.ReloadedII`

Folders.
When you next start the launcher, it should hopefully download the missing dependencies.
