### ISSUE TITLE
Bug: Report a error when I launch game

### ISSUE THREAD

**Issue by POIsona** [Reloaded-Project/Reloaded-II#288]
[Reloaded] Failed to Load Reloaded-II.
The type initializer for 'Reloaded.Hooks.Tools.Utilities' threw an exception.
   at Reloaded.Hooks.Tools.Utilities.WritePointer(UIntPtr target)
   at Reloaded.Hooks.ReloadedHooksUtilities.WritePointer(IntPtr target)
   at Reloaded.Mod.Loader.Utilities.DelayInjector..ctor(IReloadedHooks hooks, Action action, Logger logger)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
A log is available at: C:\Users\56384\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2024-02-15 06.20.23 ~ granblue_fantasy_relink.txt
Inner Exception: Appropriate FASM DLL for X86/64 has not been found in either current or library directory. |    at Reloaded.Assembler.Assembler.GetFasmDLLPath()
   at Reloaded.Assembler.Assembler..ctor(Int32 , Int32 )
   at Reloaded.Hooks.Tools.Utilities..cctor()
![QQ图片20240215142212](https://github.com/Reloaded-Project/Reloaded-II/assets/42988437/88149909-c57c-40db-a946-c84adda9e292)

**Comment by Sewer56** [comment]
Delete your `reloaded.hooks.sharedlib` folder from `Mods` folder and let launcher redownload. You probably just got a borked download.

**Comment by Sewer56** [comment]
I'm closing this for:
- https://github.com/Reloaded-Project/Reloaded-II/issues/305

Which has a bit more posts (same issue).
It's strange, but will debug soon with one of the affected folks soon once I can

**Comment by Sewer56** [comment]
Although I don't know the exact cause for this, it is now fixed in the relevant mod.
