### ISSUE TITLE
[User Has Borked Steam Files or Valve Updated Format Again]

### ISSUE THREAD

**Issue by JO2Game** [Reloaded-Project/Reloaded-II#309]
[22:24:44] [Reloaded] Create Loader | Time: 48ms
[22:24:44] [Reloaded] Loaded: reloaded.sharedlib.hooks in 12ms
[22:24:44] Warning: Steam Stub (Embedded Steam DRM) found.
This means EXE is encrypted at launch. Support for bypassing this DRM is experimental.
If you find issues, remove the DRM using `Steamless` or try using ASI Loader `Edit Application -> Deploy ASI Loader`
[22:24:44] [Reloaded] DRM Requiring Delayed Initialization (SteamStub) Found.
Reloaded will try to initialize late to bypass this DRM.
Please note this feature is experimental.
If you encounter issues, report and/or try ASI Loader `Edit Application -> Deploy ASI Loader`
[22:24:44] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[22:24:44] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[22:24:44] [R-II SteamHook] Failed to scan through Steam games and locate current game. Error: Steam Directory was not found!,    at Indieteur.SAMAPI.SteamAppsManager..ctor()
   at Reloaded.Mod.Loader.Utilities.Steam.SteamHook.DropSteamAppId(Logger logger)
[22:24:44] [Reloaded] Setting Up Hooks (Async) | Time: 144ms
[22:24:44] [Reloaded] Loading Mods (Total) | Time: 211ms
[22:24:44] [Reloaded] Total Loader Initialization Time: 284ms
[22:24:45] [Reloaded] Delay Injection via Entry Point: winmm, timeBeginPeriod
[22:24:45] [Reloaded] Loading via Delayed Injection (DRM Workaround)

**Comment by Sewer56** [comment]
I will look at this after I rewrite DLL Injection code so it hopefully stops throwing false positives from defender.
Either Valve changed the file format again, or your `.vdf` file is borked.

**Comment by Sewer56** [comment]
Okay I got more time.

Would you be able to upload your `.acf` and `.vdf` files from `Steam\steamapps`?
They contain your Steam library locations and info for each game, I want to see if it lines up with mine, in case they changed the format.

**Comment by Sewer56** [comment]
Please reopen this if you respond.
