### ISSUE TITLE
Bug: Reloaded not opening

### ISSUE THREAD

**Issue by Leonl93** [Reloaded-Project/Reloaded-II#352]
**Describe the Bug**
Hey guys, i have an issue with Reloaded while launching it (yes, the program itself not the game).  Until yesterday i was using without major issues, but today while launched "Persona 3 Reloaded" by Reloaded, my computer suddenly reset while the mods loaded and after that, everything stopped working.

1 - Received an error "JSON.exception.parse_error.101 parse error at line 1 (...) unexpected end of input (...)" at the game.
2 - When tried to open the reloaded modder, this simply don't open. I can see it for seconds at task manager, but it closes automatically. 

I deleted everything, download it again, update the version, re-downloaded the prerequisites, tried opening at sandboxie, but well... i cannot open it, it seems like something are block it and automatically close

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Reloaded folder
2. Click on the .exe 
3. Wait to open, while check at task manager
4. See the task for seconds and not open at all

**Expected Behaviour**
Is possible to recovery? Or there's something that i missed delete for opening it again?

**Screenshots**

**Additional Context**

**Comment by Sewer56** [comment]
Please post the whole error if you can.

**Comment by Leonl93** [comment]
json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

I wasn't able to get a print screen, this is what happen at the game.

But I really cannot get anything about the reloaded itself because there's no error, just don't open. 
If helps, everytime I try to install with the setup, it finishes and stops working

**Comment by Sewer56** [comment]
If a screenshot is not possible, consider recording your screen in this case :wink:

**Comment by OceanXIII** [comment]
first time commenting on github sry if doing something wrong but did you find a Soullution for the problem because i have the same for like a few days now and i dont know how to fix it

**Comment by OceanXIII** [comment]
i can send a clip if you explain how to do like i said its my first time really using github

**Comment by Sewer56** [comment]
You should be able to just drag an MP4 file over the message window. Or any file you want to upload.

**Comment by OceanXIII** [comment]
Uploading unknown_replay_2024.04.04-22.18.mp4…

**Comment by Sewer56** [comment]
You might need to wait a little bit longer.
It'll replace the 'uploading' text with the actual link when it's done.

**Comment by OceanXIII** [comment]
https://github.com/Reloaded-Project/Reloaded-II/assets/166066010/6b9d4481-f750-4dd3-a447-fe7efe068286

**Comment by Sewer56** [comment]
Okay, try this:

- Open `Event Viewer`
- Go to `Windows Logs` -> `Application`
- Find latest `Error` (red) with `.NET Runtime` as Source.
- Copy-paste the error text, or screenshot it.

(If your OS is set to German, these things might have slightly different name).

**Comment by OceanXIII** [comment]
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/166066010/d84914c7-7ff9-4ba6-909f-e10bedc8ec05)



you mean this?

**Comment by OceanXIII** [comment]
Name der fehlerhaften Anwendung: Reloaded-II.exe, Version: 1.27.1.0, Zeitstempel: 0x65cd0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3996, Zeitstempel: 0xb756c9ff
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cf19
ID des fehlerhaften Prozesses: 0x4fc4
Startzeit der fehlerhaften Anwendung: 0x01da86cd2ed21cdf
Pfad der fehlerhaften Anwendung: C:\Users\xJust1nXx\Desktop\Reloaded-II\Reloaded-II.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 21c3b233-193c-4418-81d3-0028b7216769
Vollständiger Name des fehlerhaften Pakets:

**Comment by Sewer56** [comment]
Aah, there may be 2 entries with `Error` when you get a crash. You want the other one which says `.NET Runtime` in source column. This was the other (native) one.

**Comment by Sewer56** [comment]
> ![image](https://private-user-images.githubusercontent.com/166066010/319764067-d84914c7-7ff9-4ba6-909f-e10bedc8ec05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjMwOTMsIm5iZiI6MTcxMjI2Mjc5MywicGF0aCI6Ii8xNjYwNjYwMTAvMzE5NzY0MDY3LWQ4NDkxNGM3LTdmZjktNGJhNi05MDlmLWUxMGJlZGM4ZWMwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWM1NmJjNDkzNDY5ZmRhMjVmMTMzYTBiNTRmNjc2MzlkNzUyMDNiZGY4ZWU3OTc2Y2JkYWNiNjU0ZWExMGVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.397OmTfjLO1qYIuZOcS5q6YS1O0hzyw37ebabDcZsyI)
> 
> you mean this?

I somehow missed this message.
I mean the item under this one directly.

**Comment by OceanXIII** [comment]
i send it already its the one before youre message, i can send it again tho

**Comment by Sewer56** [comment]
Might not have pasted correctly. You sent the same message twice.

**Comment by OceanXIII** [comment]
Application: Reloaded-II.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'Reloaded.Mod.Launcher.Lib.IoC' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Reloaded.Mod.Launcher.Lib.Static.Errors.HandleException(Exception ex, String message)
   at Reloaded.Mod.Launcher.Lib.IoC..cctor()
   --- End of inner exception stack trace ---
   at Reloaded.Mod.Launcher.Lib.IoC.GetConstant[T]()
   at Reloaded.Mod.Launcher.App.SetupResources()
   at Reloaded.Mod.Launcher.App.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Reloaded.Mod.Launcher.App.Main()


never mind it didnt copy it her you go

**Comment by Sewer56** [comment]
Hmm, strange.
Here's an idea, try deleting 

`%appdata%/Reloaded-Mod-Loader-II`

(It's a folder, to get to it, paste that path in your Windows Explorer window address bar).

Delete all the files in that folder.

-----&

After that, get clean Reloaded files (just in case)
https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.27.1/Release.zip

And extract all files over your current Reloaded files.

**Comment by OceanXIII** [comment]
into the folder where i delted the stuff or the normal reload folder?

**Comment by OceanXIII** [comment]
it worked omg i love you i cant thank you enough that stuff was bothering me for days i just wanted to play some games with mods

much love bro really appreciate it

**Comment by Sewer56** [comment]
Have fun :p

**Comment by OceanXIII** [comment]
i will thank you :)
