### ISSUE TITLE
"Help: Please help me with <X>

### ISSUE THREAD

**Issue by Dustyragon** [Reloaded-Project/Reloaded-II#383]
**Did you install the Prerequisites?**
Yes, I have all of the required stuff to run, I've used Reloaded for both P3R and P5R.

**Describe the Issue**
All I did was add a few mods to load into P5R and for some reason it's giving me the error that it can't load Reloaded now, which might as well negate all of the mods I wanted to use. It worked perfectly fine a couple days back only to suddenly give me an error. The game still loads, but it might as well be vanilla that loads and I'd prefer to have my mods.

**Screenshots**
I have the log file, no screenshots cause the logs will cover it. It gets to the same point each time now.

**Additional Resources**
[22:36:51] [Reloaded] Create Loader | Time: 28ms
[22:36:51] [Reloaded] Loading 1 Mod(s).
[22:36:51] [Reloaded] 
[22:36:51] [Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[22:36:51] [Reloaded] - AppId   : reloaded.sharedlib.hooks
[22:36:51] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[22:36:51] [Reloaded] - LoadTime: 5ms
[22:36:51] [Reloaded] Loaded via: C:\Users\[user]\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[22:36:51] [Reloaded] Current Process Location: F:\Steam\steamapps\common\P5R\P5R.exe
[22:36:51] [Reloaded] Loading 29 Mod(s).
[22:36:51] [Reloaded] 
[22:36:51] [Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[22:36:51] [Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[22:36:51] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[22:36:51] [Reloaded] - LoadTime: 5ms
[22:36:51] [Reloaded] 
[22:36:51] [Reloaded] Loading: CRI FileSystem V2 Hook
[22:36:51] [Reloaded] - AppId   : crifs.v2.hook
[22:36:51] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\crifs.v2.hook\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 32ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: File Emulation Framework: Base Mod
[22:36:52] [Reloaded] - AppId   : reloaded.universal.fileemulationframework
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
[22:36:52] Starting FileEmulationFramework
[22:36:52] [R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[22:36:52] [R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[22:36:52] [Reloaded] - LoadTime: 55ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: AWB Emulator for File Emulation Framework
[22:36:52] [Reloaded] - AppId   : reloaded.universal.fileemulationframework.awb
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.awb\ModConfig.json
[22:36:52] Starting AWB.Stream.Emulator
[22:36:52] [Reloaded] - LoadTime: 12ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: AWB Emulator Support for CRI FileSystem V2 Hook
[22:36:52] [Reloaded] - AppId   : CriFs.V2.Hook.Awb
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\CriFs.V2.Hook.Awb\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 9ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: PAK Emulator for File Emulation Framework
[22:36:52] [Reloaded] - AppId   : reloaded.universal.fileemulationframework.pak
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.pak\ModConfig.json
[22:36:52] Starting PAK.Stream.Emulator
[22:36:52] [Reloaded] - LoadTime: 10ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: BMD Emulator For File Emulation Framework
[22:36:52] [Reloaded] - AppId   : reloaded.universal.fileemulationframework.bmd
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bmd\ModConfig.json
[22:36:52] [Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[22:36:52] Starting BMD.File.Emulator
[22:36:52] [R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.
[22:36:52] [Reloaded] Setting Up Hooks (Async) | Time: 330ms
[22:36:52] [Reloaded] - LoadTime: 362ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: BF Emulator for File Emulation Framework
[22:36:52] [Reloaded] - AppId   : reloaded.universal.fileemulationframework.bf
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bf\ModConfig.json
[22:36:52] [Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[22:36:52] Starting BF.File.Emulator
[22:36:52] [Reloaded] - LoadTime: 227ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: SPD Emulator for File Emulation Framework
[22:36:52] [Reloaded] - AppId   : reloaded.universal.fileemulationframework.spd
[22:36:52] [Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.spd\ModConfig.json
[22:36:52] Starting SPD.File.Emulator
[22:36:52] [Reloaded] - LoadTime: 10ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Persona Essentials
[22:36:52] [Reloaded] - AppId   : p5rpc.modloader
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.modloader\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 8ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Persona 5 Royal Library
[22:36:52] [Reloaded] - AppId   : p5rpc.lib
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.lib\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 23ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: BGME Framework API
[22:36:52] [Reloaded] - AppId   : BGME.Framework.API
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\BGME.Framework.API\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 20ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: BGME Framework
[22:36:52] [Reloaded] - AppId   : BGME.Framework
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\BGME.Framework\ModConfig.json
[22:36:52] [BGME Framework] [INF] Music loaded.
[22:36:52] [Reloaded] - LoadTime: 77ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Audio Mix Control
[22:36:52] [Reloaded] - AppId   : p5rpc.audiomixcontrol
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.audiomixcontrol\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 3ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Inaba Exe Patcher
[22:36:52] [Reloaded] - AppId   : p4gpc.inaba
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p4gpc.inaba\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 3ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: AI Tactics Fixes
[22:36:52] [Reloaded] - AppId   : p5rpc.v.tactics
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.v.tactics\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 7ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Classroom Cheat Sheet
[22:36:52] [Reloaded] - AppId   : p5rpc.misc.classroomcheatsheet
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.misc.classroomcheatsheet\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Conditioned to Hate (FFXV) over Will Power
[22:36:52] [Reloaded] - AppId   : p5rpc.music.conditionedtowillpower
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.music.conditionedtowillpower\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 11ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Confidant Cheat Sheet
[22:36:52] [Reloaded] - AppId   : p5rpc.misc.confidantcheatsheet
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.misc.confidantcheatsheet\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Crossword Puzzle Cheat Sheet
[22:36:52] [Reloaded] - AppId   : p5rpc.CrosswordCheat
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.CrosswordCheat\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Expanded Square Button
[22:36:52] [Reloaded] - AppId   : p5rpc.ExpandedSquareButton
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.ExpandedSquareButton\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 7ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Guard Regeneration + Ammo Refill in Battle
[22:36:52] [Reloaded] - AppId   : p5rpc.guardregen
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.guardregen\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 4ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Its going down now over Take over
[22:36:52] [Reloaded] - AppId   : Its gping down now over Take over
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\Its gping down now over Take over\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Negotiation Cheat Sheet
[22:36:52] [Reloaded] - AppId   : p5rpc.events.negotiationcheatsheet
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.events.negotiationcheatsheet\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: TV Quiz Cheat Sheet
[22:36:52] [Reloaded] - AppId   : p5rpc.misc.TVQuizCheatSheet
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.misc.TVQuizCheatSheet\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Umbreon over Cat Mona
[22:36:52] [Reloaded] - AppId   : P5RUmbreonMona
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\P5RUmbreonMona\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Deep Stone Crypt
[22:36:52] [Reloaded] - AppId   : Deep Stone Crypt
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\Deep Stone Crypt\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 1ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: Vow of the Disciple Skills Pack
[22:36:52] [Reloaded] - AppId   : Vow of the Disciple
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\Vow of the Disciple\ModConfig.json
[22:36:52] [Reloaded] - LoadTime: 0ms
[22:36:52] [Reloaded] 
[22:36:52] [Reloaded] Loading: DOOMSona
[22:36:52] [Reloaded] - AppId   : p5rpc.addon.doomsona
[22:36:52] [Reloaded] - Location: C:\Users\[user]\Desktop\Reloaded-II\Mods\p5rpc.addon.doomsona\ModConfig.json
[22:36:53] [Reloaded] - LoadTime: 143ms
[22:36:53] Matched best signature set 'Persona 5 Royal' by version string: 'CRI File System/PCx64 Ver.2.81.6 Build:Dec 28 2021 11:03:45'
[22:36:53] ----- CRIFsV2Hook Analysis -----
[22:36:53] Closest CRI Version: CRI File System/PCx64 Ver.2.81.6 Build:Dec 28 2021 11:03:45
[22:36:53] Compiler: MSC19.00.24210.0,MT
[22:36:53] Sourced From: Persona 5 Royal
[22:36:53] Signature Found: criFs_CalculateWorkSizeForLibrary at 1405198A4
[22:36:53] Signature Found: criFs_FinalizeLibrary at 140519C5C
[22:36:53] Signature Found: criFs_InitializeLibrary at 14051A098
[22:36:53] Signature Found: criFsBinder_BindCpk at 1405125B4
[22:36:53] Signature Found: criFsBinder_BindFile at 1405127CC
[22:36:53] Signature Found: criFsBinder_BindFiles at 1405127F8
[22:36:53] Signature Found: criFsBinder_Find at 140512EC8
[22:36:53] Signature Found: criFsBinder_GetWorkSizeForBindFiles at 1405144B4
[22:36:53] Signature Found: criFsBinder_SetPriority at 140514BBC
[22:36:53] Signature Found: criFsBinder_GetStatus at 14051426C
[22:36:53] Signature Found: criFsBinder_Unbind at 140514DBC
[22:36:53] Signature Found: criFsLoader_RegisterFile at 140519144
[22:36:53] Signature Found: criFsIo_Open at 1405251DC
[22:36:53] Signature Found: criFsIo_Exists at 140524FE4
[22:36:53] Signature Found: Is UTF8 Flag. at 1429DE990
[22:36:53] ----- CRIFsV2Hook Analysis -----
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_Create found at: 14048B1F8
[22:36:53] [BGME Framework] [INF] criAtomExAcb_LoadAcbFile found at: 140488854
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetCueId found at: 14048D4B8
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetStartTime found at: 14048E4B4
[22:36:53] [BGME Framework] [INF] criAtomExPlayback_GetTimeSyncedWithAudio found at: 140489F94
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_GetNumPlayedSamples found at: 14050B988
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_Start found at: 14048E780
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetFile found at: 14048DA90
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetFormat found at: 14048DB9C
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetSamplingRate found at: 14048E208
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetNumChannels found at: 14048DD64
[22:36:53] [BGME Framework] [INF] criAtomExCategory_GetVolumeById found at: 14047B234
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetVolume found at: 14048E6C0
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_SetCategoryById found at: 14048D1B0
[22:36:53] [BGME Framework] [INF] criAtomExPlayer_GetLastPlaybackId found at: 14048C064
[22:36:53] [BGME Framework] [INF] Play BGM Function found at: 155966B00
[22:36:53] [BGME Framework] [INF] Encounter BGM found at: 1409786EB
[22:36:53] [BGME Framework] [INF] Victory BGM found at: 140996D38
[22:36:53] [BGME Framework] [INF] Victory BGM on Victory found at: 14099D2B0
[22:36:53] [BGME Framework] [INF] BIT_CHK found at: 140E29310
[22:36:53] [Reloaded] Failed to Load Reloaded-II.
BgmPlay function signature not found.
   at p5rpc.audiomixcontrol.Mod.<>c__DisplayClass17_0.<AddSigScan>b__0(PatternScanResult result)
   at Reloaded.Memory.SigScan.ReloadedII.StartupScanner.RunMainModuleScans()
   at Reloaded.Memory.SigScan.ReloadedII.StartupScanner.OnLoaderInitialized()
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by Sewer56** [comment]
Just woke up.

Getting thrown by Audio Mix Control.
(CC @osyu) :point_left: mod author

Either due to mod being outdated with game version, or due to conflict by not using proper procedure. (Always possible someone chose not to use startup scanner and signature scan failed).

Do try toggling DOOMSona on/off as it doesn't use the startup scanner, maybe it's that.

**Comment by Dustyragon** [comment]
Got it, I'll disable DOOMScanner for now then. Thank you.
