### ISSUE TITLE
[UnrealEssentials not recognising SMT5V on user's machine]

### ISSUE THREAD

**Issue by fmalust** [Reloaded-Project/Reloaded-II#397]
[23:40:01] [Reloaded] Create Loader | Time: 51ms
[23:40:01] [Reloaded] Loading 1 Mod(s).
[23:40:01] [Reloaded] 
[23:40:01] [Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[23:40:01] [Reloaded] - AppId   : reloaded.sharedlib.hooks
[23:40:01] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[23:40:01] [Reloaded] - LoadTime: 11ms
[23:40:01] [Reloaded] Loaded via: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[23:40:01] [Reloaded] Current Process Location: D:\Program Files (x86)\Steam\steamapps\common\SMT5V\SMT5V.exe
[23:40:01] [Reloaded] Loading 8 Mod(s).
[23:40:01] [Reloaded] 
[23:40:01] [Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[23:40:01] [Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[23:40:01] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[23:40:01] [Reloaded] - LoadTime: 13ms
[23:40:01] [Reloaded] 
[23:40:01] [Reloaded] Loading: Shared Scans
[23:40:01] [Reloaded] - AppId   : SharedScans.Reloaded
[23:40:01] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\SharedScans.Reloaded\ModConfig.json
[23:40:01] [Reloaded] - LoadTime: 20ms
[23:40:01] [Reloaded] 
[23:40:01] [Reloaded] Loading: File Emulation Framework: Base Mod
[23:40:01] [Reloaded] - AppId   : reloaded.universal.fileemulationframework
[23:40:01] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
[23:40:01] Starting FileEmulationFramework
[23:40:01] [Reloaded] Setting Up Hooks (Async) | Time: 136ms
[23:40:01] [Reloaded] - LoadTime: 89ms
[23:40:01] [Reloaded] 
[23:40:01] [Reloaded] Loading: IO Store Emulator
[23:40:01] [Reloaded] - AppId   : UTOC.Stream.Emulator
[23:40:01] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\UTOC.Stream.Emulator\ModConfig.json
[23:40:01] [Reloaded] - LoadTime: 12ms
[23:40:01] [Reloaded] 
[23:40:01] [Reloaded] Loading: Unreal Essentials
[23:40:01] [Reloaded] - AppId   : UnrealEssentials
[23:40:01] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\UnrealEssentials\ModConfig.json
[23:40:01] Error while starting mod: UnrealEssentials
[23:40:01] [Reloaded] Failed to Load Reloaded-II.
Unable to find Unreal Engine version number.
Please report this!
   at UnrealEssentials.Mod.GetSignatures()
   at UnrealEssentials.Mod..ctor(ModContext context)
   at UnrealEssentials.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)
A log is available at: C:\Users\chris\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2024-06-20 04.40.01 ~ SMT5V.txt
[23:41:33] [Reloaded] ExitProcess Hook: Log End

**To Reproduce**
1. Launch Reloaded-II
2. Launch Application (Shin Megami Tensei V - Vengeance
3. See error

Only using two mods, Da'at Battle Theme by DeathChaos and Catherine Font by Century_

**Comment by Sewer56** [comment]
CC @AnimatedSwine37

**Comment by AnimatedSwine37** [comment]
Are you on the [latest version](https://github.com/AnimatedSwine37/UnrealEssentials/releases/latest) of Unreal Essentials (1.1.1)?
If you are then are you playing on Steam or the Microsoft Store version?

**Comment by Sewer56** [comment]
`Current Process Location: D:\Program Files (x86)\Steam\steamapps\common\SMT5V\SMT5V.exe`

They're playing Steam

**Comment by fmalust** [comment]
I don't think I was, but I went ahead and updated it to 1.1.1 thanks to you. I am using Steam, as Sewer56 mentioned, but I got what seems to be the same error after updating Unreal Essentials to 1.1.1.

[05:14:08] [Reloaded] Create Loader | Time: 45ms
[05:14:08] [Reloaded] Loading 1 Mod(s).
[05:14:08] [Reloaded] 
[05:14:08] [Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[05:14:08] [Reloaded] - AppId   : reloaded.sharedlib.hooks
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[05:14:08] [Reloaded] - LoadTime: 10ms
[05:14:08] [Reloaded] Loaded via: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[05:14:08] [Reloaded] Current Process Location: D:\Program Files (x86)\Steam\steamapps\common\SMT5V\SMT5V.exe
[05:14:08] [Reloaded] Loading 8 Mod(s).
[05:14:08] [Reloaded] 
[05:14:08] [Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[05:14:08] [Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[05:14:08] [Reloaded] - LoadTime: 9ms
[05:14:08] [Reloaded] 
[05:14:08] [Reloaded] Loading: File Emulation Framework: Base Mod
[05:14:08] [Reloaded] - AppId   : reloaded.universal.fileemulationframework
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
[05:14:08] Starting FileEmulationFramework
[05:14:08] [Reloaded] - LoadTime: 100ms
[05:14:08] [Reloaded] Setting Up Hooks (Async) | Time: 121ms
[05:14:08] [Reloaded] 
[05:14:08] [Reloaded] Loading: IO Store Emulator
[05:14:08] [Reloaded] - AppId   : UTOC.Stream.Emulator
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\UTOC.Stream.Emulator\ModConfig.json
[05:14:08] [Reloaded] - LoadTime: 12ms
[05:14:08] [Reloaded] 
[05:14:08] [Reloaded] Loading: Unreal Essentials
[05:14:08] [Reloaded] - AppId   : UnrealEssentials
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\UnrealEssentials\ModConfig.json
[05:14:09] Error while starting mod: UnrealEssentials
[05:14:09] [Reloaded] Failed to Load Reloaded-II.
Unable to find Unreal Engine version number.
Please report this!
   at UnrealEssentials.Mod.GetSignatures()
   at UnrealEssentials.Mod..ctor(ModContext context)
   at UnrealEssentials.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by fmalust** [comment]
I don't think I was, but I went ahead and updated it to 1.1.1 thanks to you. I am using Steam, as Sewer56 mentioned, but I got what seems to be the same error after updating Unreal Essentials to 1.1.1.

[05:14:08] [Reloaded] Create Loader | Time: 45ms
[05:14:08] [Reloaded] Loading 1 Mod(s).
[05:14:08] [Reloaded]
[05:14:08] [Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[05:14:08] [Reloaded] - AppId : reloaded.sharedlib.hooks
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[05:14:08] [Reloaded] - LoadTime: 10ms
[05:14:08] [Reloaded] Loaded via: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[05:14:08] [Reloaded] Current Process Location: D:\Program Files (x86)\Steam\steamapps\common\SMT5V\SMT5V.exe
[05:14:08] [Reloaded] Loading 8 Mod(s).
[05:14:08] [Reloaded]
[05:14:08] [Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[05:14:08] [Reloaded] - AppId : Reloaded.Memory.SigScan.ReloadedII
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[05:14:08] [Reloaded] - LoadTime: 9ms
[05:14:08] [Reloaded]
[05:14:08] [Reloaded] Loading: File Emulation Framework: Base Mod
[05:14:08] [Reloaded] - AppId : reloaded.universal.fileemulationframework
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
[05:14:08] Starting FileEmulationFramework
[05:14:08] [Reloaded] - LoadTime: 100ms
[05:14:08] [Reloaded] Setting Up Hooks (Async) | Time: 121ms
[05:14:08] [Reloaded]
[05:14:08] [Reloaded] Loading: IO Store Emulator
[05:14:08] [Reloaded] - AppId : UTOC.Stream.Emulator
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\UTOC.Stream.Emulator\ModConfig.json
[05:14:08] [Reloaded] - LoadTime: 12ms
[05:14:08] [Reloaded]
[05:14:08] [Reloaded] Loading: Unreal Essentials
[05:14:08] [Reloaded] - AppId : UnrealEssentials
[05:14:08] [Reloaded] - Location: C:\Users\chris\OneDrive\Desktop\Reloaded-II\Mods\UnrealEssentials\ModConfig.json
[05:14:09] Error while starting mod: UnrealEssentials
[05:14:09] [Reloaded] Failed to Load Reloaded-II.
Unable to find Unreal Engine version number.
Please report this!
at UnrealEssentials.Mod.GetSignatures()
at UnrealEssentials.Mod..ctor(ModContext context)
at UnrealEssentials.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List1 modPaths) at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable1 modsToLoad, List`1 allMods)
at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.b__1()
at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**Comment by Sewer56** [comment]
@AnimatedSwine37 We should maybe add a warning via the Community Repo, [like this one](https://github.com/Reloaded-Project/Reloaded.Community/blob/main/Apps/Sonic%20Heroes/Launcher.json). Might help prevent this in the future.

**Comment by AnimatedSwine37** [comment]
I did think about doing that but I wasn't sure how, making a separate app like that that's just bad makes sense.

**Comment by AnimatedSwine37** [comment]
There you go, hopefully this will stop people from getting confused
https://github.com/Reloaded-Project/Reloaded.Community/pull/14

**Comment by Sewer56** [comment]
:+1: done.
We can probably close this.

I'll wait for original person to reply, but we should be good.

**Comment by fmalust** [comment]
Oh my goodness. Thank you so much; I'm sorry if I was being confusing and I totally had no idea either. The mods all work now. Thank you both so much!

**Comment by Sewer56** [comment]
No worries, get out there, and have fun :p
