### ISSUE TITLE
Reloaded II not opening

### ISSUE THREAD

**Issue by TheGrassLad** [Reloaded-Project/Reloaded-II#420]
when I run "Reloaded-II.exe" nothing happens. I tried disabling windows defender which worked for me before, and also tried running it in admin. I also tried reinstalling it.
I checked event viewer and I can see two messages:

1.
Application: Reloaded-II.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Reloaded.Mod.Loader.IO, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Reloaded.Mod.Loader.IO, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'
   at Reloaded.Mod.Launcher.App.SetupResources()
   at Reloaded.Mod.Launcher.App.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Reloaded.Mod.Launcher.App.Main()

2.
Faulting application name: Reloaded-II.exe, version: 1.27.12.0, time stamp: 0x66960000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4291, time stamp: 0xa956ff71
Exception code: 0xe0434352
Fault offset: 0x000000000002ab89
Faulting process id: 0x6fc
Faulting application start time: 0x01daf390d34a68e5
Faulting application path: C:\Users\raymo\Downloads\Release\Reloaded-II.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 76ecffd5-35e0-4ce8-8d4f-ff4905c88bb2
Faulting package full name: 
Faulting package-relative application ID:

**Comment by TheGrassLad** [comment]
I tried to reinstall it again and that fixed it. Not sure why it didn't work the first time I tried it though.
