### ISSUE TITLE
Bug: <mods causing all kinds of issues> when <launching application>

### ISSUE THREAD

**Issue by Atomik-a** [Reloaded-Project/Reloaded-II#464]
**Describe the Bug**
[Reloaded] DLL Not Found! CriFs.V2.Hook.dll
Mod Name: CRI FileSystem V2 Hook, Mod ID: crifs.v2.hook
Please re-download the mod. It is either corrupt or you may have downloaded the source code by accident.
[Reloaded]
[Reloaded] Loading: CRI FileSystem V2 Hook
[Reloaded] - AppId   : crifs.v2.hook
[Reloaded] - Location: C:\Users\swagi\OneDrive\Desktop\Reloaded-II\Mods\crifs.v2.hook\ModConfig.json
[Reloaded] - LoadTime: 0ms
[Reloaded]
[Reloaded] Loading: AWB Emulator Support for CRI FileSystem V2 Hook
[Reloaded] - AppId   : CriFs.V2.Hook.Awb
[Reloaded] - Location: C:\Users\swagi\OneDrive\Desktop\Reloaded-II\Mods\CriFs.V2.Hook.Awb\ModConfig.json
[Reloaded] [LoaderAPI] Warning: GetController<ICriFsRedirectorApi> returned null.
Error while starting mod: CriFs.V2.Hook.Awb
[Reloaded] Failed to Load Reloaded-II.
Object reference not set to an instance of an object.
   at CriFs.V2.Hook.Awb.Mod..ctor(ModContext context)
   at CriFs.V2.Hook.Awb.Template.Startup.StartEx(IModLoaderV1 loaderApi, IModConfigV1 modConfig)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'mod configuration'
2. Click on 'launch application'

**Expected Behaviour**
Mods work on launch

**Comment by Sewer56** [comment]
I checked the file to download; doesn't seem to be borked.

Delete the folder `CriFs.V2.Hook` from your Reloaded-II's `Mods` folder.
Chances are you just had a bad download on your end.

Also consider checking your Antivirus logs; in case the AV accidentally deleted it after update.

**Comment by Atomik-a** [comment]
ty I i deleted the CriFs.V2.Hook folder and it worked.
