### ISSUE TITLE
Bug: Linux Installer not working on Mint

### ISSUE THREAD

**Issue by j3nesis87** [Reloaded-Project/Reloaded-II#486]
When using the Linux Installer (https://github.com/Reloaded-Project/Reloaded-II/releases/latest/download/Setup-Linux.exe), it does not work for me. 

**To Reproduce**
OS: Mint 22 Cinnamon
Install desired game (P5R in this case) through Steam, run once to generate prefix
Download Setup-Linux.exe
Run through Protontricks and the P5R prefix
A folder and a shortcut appear on my desktop
Open shortcut, get prompt to "Run anyway" or "Trust", either option gives same result
...Nothing happens

**Expected Behaviour**
Reloaded to run

**Additional Context**
I have tried going into the created desktop folder and running Reloaded-II.exe through the P5R prefix, it tries to start, but I get a "You must install or update .NET" error, and cannot continue. 

**Notes**

Edit to add: I tried running the bash command from the shortcut directly in Terminal. I get this:

bash -ic 'protontricks-launch --appid 1687950 "/home/jenny/Desktop/Reloaded-II - P5R/Reloaded-II.exe"'
Traceback (most recent call last):
  File "/usr/bin/protontricks-launch", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/cli/launch.py", line 18, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/cli/launch.py", line 187, in main
    cli_main(cli_args, steam_path=steam_path, steam_root=steam_root)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 329, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 821, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 540, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

**Comment by Sewer56** [comment]
From what I gather in the traceback, protontricks is unable to launch anything from an appid because some file on the system out there is probably borked.

I don't really know which, unfortunately.
I would suggest filing this issue to protontricks, someone in there might be able to figure out faster than I would.
