### ISSUE TITLE
Help: Could not find Util "Open_File"

### ISSUE THREAD

**Issue by CD213** [Reloaded-Project/Reloaded-II#489]
Whenever I launch the application, I get this pop up. 

[22:39:27] [Reloaded] Failed to Load Reloaded-II.
Could not find Util "Open_File"
   at Unhardcoded_P5R.Utils.<>c__DisplayClass24_0.<.ctor>b__0(PatternScanResult result) in C:\Users\Gabriel Premore\source\repos\Colored_Chat_Icon_Bg\Utils.cs:line 53
   at Reloaded.Memory.SigScan.ReloadedII.StartupScanner.RunMainModuleScans()
   at Reloaded.Memory.SigScan.ReloadedII.StartupScanner.OnLoaderInitialized()
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
   at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)

I don't really know how to resolve it, any help would be very much appreciated.

**Comment by Sewer56** [comment]
The coloured chat icon background mod was not updated for the latest version of Persona 5 Royal. You're either using that mod directly, or it's a dependency of another mod ypu have installed.
