### ISSUE TITLE
Bug: Timoutlimit exceeded when i try to launch

### ISSUE THREAD

**Issue by imbadatthi1s** [Reloaded-Project/Reloaded-II#64]
**Describe the Bug**

whenever i try to launch reloaded to play persona with mods it gets this error
![image](https://user-images.githubusercontent.com/75858598/101944863-4f5d5b80-3be5-11eb-93d2-393218636703.png)

i don't understand what it means and i was able to launch with mods before, it just stopped working alll of a sudden.

**Comment by Sewer56** [comment]
Basically for whatever reason the game is crashing on launch and the launcher, which tries to connect to the loader inside the game to load/unload/reload mods while the game is running doesn't get the chance to connect in 30 seconds (30000ms) and it times out trying.

I recommend checking your mod list and seeing if the game launches without any mods enabled via Reloaded. (this includes modloader)

If it does, it may be mod specific and I'd suggest individually enabling/disabling mods to find the culprit.

**Comment by TheOct0** [comment]
Hi! I was about to open an issue for that exact same problem, but I might as well comment here.
I've tried everything I could think of: reinstalling every dependencies, reinstalling Reloaded, Persona, launching with no mods, only some, and so on... This issue used to be solved by just making a clean Reloaded install and reconfiguring everything, but now I can't get it to work under any circumstances.

I'm very much at a loss here. Plus, the game launches a short while after this message, so this musntn't have anything to do with P4G crashing. Weird.

**Comment by TheOct0** [comment]
```
Log Name:      Application
Source:        Application Error
Date:          16/12/2020 23:31:00
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-L339CMM
Description:
Faulting application name: Reloaded-II32.exe, version: 1.7.2.0, time stamp: 0x5f17576d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xe6477cce
Exception code: 0xe0434352
Fault offset: 0x0012a892
Faulting process ID: 0x3fa4
Faulting application start time: 0x01d6d3fb09432478
Faulting application path: D:\Users\maelq\Documents\Reloaded-II\Reloaded-II32.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 47a009cf-ebac-4a96-a748-0f6f80ffb644
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-12-16T22:31:00.4230935Z" />
    <EventRecordID>22903</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-L339CMM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Reloaded-II32.exe</Data>
    <Data>1.7.2.0</Data>
    <Data>5f17576d</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.662</Data>
    <Data>e6477cce</Data>
    <Data>e0434352</Data>
    <Data>0012a892</Data>
    <Data>3fa4</Data>
    <Data>01d6d3fb09432478</Data>
    <Data>D:\Users\maelq\Documents\Reloaded-II\Reloaded-II32.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>47a009cf-ebac-4a96-a748-0f6f80ffb644</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          16/12/2020 23:30:59
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-L339CMM
Description:
Application: Reloaded-II32.exe
CoreCLR Version: 4.700.20.51601
.NET Core Version: 3.1.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Timeout limit 30000 exceeded.
   at Reloaded.Mod.Launcher.Utility.ActionWrappers.TryGetValueWhile[T](Func`1 getValue, Func`1 whileFunction, Int32 timeout, Int32 sleepTime, CancellationToken token)
   at Reloaded.Mod.Launcher.Utility.ApplicationInjector.Inject()
   at Reloaded.Mod.Launcher.Utility.ApplicationLauncher.Start()
   at Reloaded.Mod.Launcher.Pages.BaseSubpages.ApplicationPage.LaunchApplication_PreviewMouseDown(Object sender, MouseButtonEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Reloaded.Mod.Launcher.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-12-16T22:30:59.9180901Z" />
    <EventRecordID>22902</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-L339CMM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Reloaded-II32.exe
CoreCLR Version: 4.700.20.51601
.NET Core Version: 3.1.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Timeout limit 30000 exceeded.
   at Reloaded.Mod.Launcher.Utility.ActionWrappers.TryGetValueWhile[T](Func`1 getValue, Func`1 whileFunction, Int32 timeout, Int32 sleepTime, CancellationToken token)
   at Reloaded.Mod.Launcher.Utility.ApplicationInjector.Inject()
   at Reloaded.Mod.Launcher.Utility.ApplicationLauncher.Start()
   at Reloaded.Mod.Launcher.Pages.BaseSubpages.ApplicationPage.LaunchApplication_PreviewMouseDown(Object sender, MouseButtonEventArgs e)
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Reloaded.Mod.Launcher.App.Main()
</Data>
  </EventData>
</Event>
```
