### ISSUE TITLE
Sonic Heroes not launching

### ISSUE THREAD

**Issue by Josielovania** [Reloaded-Project/Reloaded-II#99]
```
[00:45:24] [Reloaded] Create Loader | Time: 76ms
[00:45:24] [Reloaded] Setting Up Hooks (Async) | Time: 346ms
[00:45:24] [Reloaded] Create Loader Host (Async) | Time: 453ms
[00:45:25] [Reloaded] Loading Assembly Metadata for Inter Mod Communication, Determining Unload Support etc.: Complete 346ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.skins.hdtextures: Complete 0ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.gamefiles.characteroverhaul: Complete 0ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.guis.widescreenrevamp: Complete 0ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.gamefiles.stagefix.ver.a: Complete 0ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.audio.dialoguevolumefix: Complete 0ms
[00:45:25] [Reloaded] Prepared Mod: reloaded.sharedlib.csharp.prs: Complete 3ms
[00:45:25] [Reloaded] Prepared Mod: sonicadventureengine.physicsswap: Complete 3ms
[00:45:25] [Reloaded] Prepared Mod: criware.filesystem.hook: Complete 4ms
[00:45:25] [Reloaded] Prepared Mod: reloaded.sharedlib.hooks: Complete 4ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.utils.unlimitedobjectdrawdistance: Complete 4ms
[00:45:25] [Reloaded] Prepared Mod: reloaded.universal.redirector: Complete 4ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.utils.toner: Complete 5ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.controller.hook: Complete 5ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.utils.discordrpc: Complete 2ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.essentials.graphics: Complete 6ms
[00:45:25] [Reloaded] Prepared Mod: sonicheroes.controller.hook.xinput: Complete 3ms
[00:45:25] [Reloaded] Prepare All Mods (Total): Complete 7ms
[00:45:25] [Reloaded] Initialized Mod: reloaded.sharedlib.hooks: Complete 0ms
[00:45:25] [Reloaded] Initialized Mod: reloaded.sharedlib.csharp.prs: Complete 5ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.utils.toner: Complete 198ms
[00:45:25] [CriFsHook] Successfully hooked BuildFileTableFnPtr at 6D63B0
[00:45:25] [CriFsHook] Successfully hooked GetFileEntryFromFilePathFnPtr at 6D00F0
[00:45:25] [Reloaded] Initialized Mod: criware.filesystem.hook: Complete 43ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.essentials.graphics: Complete 52ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.skins.hdtextures: Complete 0ms
[00:45:25] [Reloaded] Initialized Mod: reloaded.universal.redirector: Complete 7ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.guis.widescreenrevamp: Complete 5ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.gamefiles.characteroverhaul: Complete 0ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.utils.unlimitedobjectdrawdistance: Complete 5ms
[00:45:25] [Reloaded] Initialized Mod: sonicadventureengine.physicsswap: Complete 0ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.gamefiles.stagefix.ver.a: Complete 0ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.audio.dialoguevolumefix: Complete 0ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.controller.hook: Complete 134ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.controller.hook.xinput: Complete 60ms
[00:45:25] [Reloaded] Initialized Mod: sonicheroes.utils.discordrpc: Complete 34ms
[00:45:25] [Reloaded] Initialized All Mods (Total): Complete 552ms
[00:45:25] [Reloaded] Loading Mods (Total) | Time: 1159ms
[00:45:25] [Reloaded] Total Loader Initialization Time: 1237ms
[00:45:25] [CriFsHook] Ignoring Build File Table
[00:45:25] [CriFsHook] Ignoring Build File Table
[00:45:25] [CriFsHook] Ignoring Build File Table
[00:45:25] [CriFsHook] Ignoring Build File Table
[00:45:25] [Reloaded] Unhandled Exception: Unable to load DLL 'dlang-prs32.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
Stack Trace:    at csharp_prs.Prs32.Estimate(IntPtr data, Int32 length)
   at csharp_prs.Prs.Estimate(Byte* data, Int32 dataLength)
   at csharp_prs.PrsInstance.Estimate(Byte* data, Int32 dataLength)
   at sonicheroes.utils.toner.Toner.GetSizeOfFile(Int32 fileIndex, OneFile& thisPointer)
   at sonicheroes.utils.toner.Toner.LoadTextureDictionary(Int32 fileIndex, Void* addressToDecompressTo, OneFile& thisPointer)
[00:45:27] [Reloaded] ExitProcess Hook: Log End
```

I've been having this issue while attempting to launch Sonic Heroes through Reloaded. Each time I launch the game, it will stay open for about one second and then immediately close. I've tried reinstalling both the mod loader and the game itself on multiple occasions and nothing has managed to fix it.

**Comment by Sewer56** [comment]
Consider checking your antivirus logs.
Maybe an AV deleted the file for whatever reason.

**Comment by ElMaisi** [comment]
Sonic Heroes works before install the loader? If its right, try to make an exception in your antivirus.

**Comment by banana3333** [comment]
I'm having the same issue but with a different log. 

> [16:40:10] [Reloaded] Create Loader | Time: 66ms
[16:40:10] [Reloaded] Setting Up Hooks (Async) | Time: 62ms
[16:40:10] [Reloaded] Loading Assembly Metadata for Inter Mod Communication, Determining Unload Support etc.: Complete 15ms
[16:40:10] [Reloaded] Prepared Mod: reloaded.sharedlib.hooks: Complete 2ms
[16:40:10] [Reloaded] Create Loader Host (Async) | Time: 67ms
[16:40:10] [Reloaded] Prepared Mod: sonicheroes.essentials.graphics: Complete 5ms
[16:40:10] [Reloaded] Prepare All Mods (Total): Complete 6ms
[16:40:10] [Reloaded] Initialized Mod: reloaded.sharedlib.hooks: Complete 0ms
[16:40:10] [Reloaded] Initialized Mod: sonicheroes.essentials.graphics: Complete 75ms
[16:40:10] [Reloaded] Initialized All Mods (Total): Complete 75ms
[16:40:10] [Reloaded] Loading Mods (Total) | Time: 146ms
[16:40:10] [Reloaded] Total Loader Initialization Time: 214ms
[16:40:12] [Reloaded] ExitProcess Hook: Log End
Fatal error. 0xC0000005
       at Reloaded.Mod.Loader.Utilities.ProcessExitHook.ExitProcessImp|(Uint32)
